# Generated by Django 6.0.1 on 2026-02-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default='thumbnails/placeholder.jpg', upload_to='thumbnail/'),
            preserve_default=False,
        ),
    ]
