# Generated by Django 6.0.1 on 2026-02-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(default='videos/placeholder.mp4', upload_to='videos/'),
            preserve_default=False,
        ),
    ]
